import xml.etree.ElementTree as ET
import json
import os

XML_RAW = r"""<ENVELOPE>
 <BILLFIXED><BILLDATE>12-Dec-25</BILLDATE><BILLREF>MDLZ/1</BILLREF><BILLPARTY>MANOJ KIRANA SEC 14</BILLPARTY></BILLFIXED>
 <BILLCL>-2030.00</BILLCL><BILLDUE>12-Dec-25</BILLDUE><BILLOVERDUE>113</BILLOVERDUE>
 <BILLFIXED><BILLDATE>13-Dec-25</BILLDATE><BILLREF>MDLZ/2</BILLREF><BILLPARTY>MAYANK TRADERS SEC-4</BILLPARTY></BILLFIXED>
 <BILLCL>-8475.00</BILLCL><BILLDUE>13-Dec-25</BILLDUE><BILLOVERDUE>112</BILLOVERDUE>
 <BILLFIXED><BILLDATE>15-Dec-25</BILLDATE><BILLREF>MDLZ/3</BILLREF><BILLPARTY>NEW BHERUNATH DUTH DAIRY</BILLPARTY></BILLFIXED>
 <BILLCL>-1691.00</BILLCL><BILLDUE>15-Dec-25</BILLDUE><BILLOVERDUE>110</BILLOVERDUE>
 <BILLFIXED><BILLDATE>22-Dec-25</BILLDATE><BILLREF>CDM/DEC25/9</BILLREF><BILLPARTY>MAHAVEER KIRANA STOREA</BILLPARTY></BILLFIXED>
 <BILLCL>-2446.00</BILLCL><BILLDUE>22-Dec-25</BILLDUE><BILLOVERDUE>103</BILLOVERDUE>
 <BILLFIXED><BILLDATE>24-Dec-25</BILLDATE><BILLREF>CDM/DEC25/44</BILLREF><BILLPARTY>JAY BHERAV DERY-Sect-11</BILLPARTY></BILLFIXED>
 <BILLCL>-1287.00</BILLCL><BILLDUE>24-Dec-25</BILLDUE><BILLOVERDUE>101</BILLOVERDUE>
 <BILLFIXED><BILLDATE>24-Dec-25</BILLDATE><BILLREF>CDM/DEC25/72</BILLREF><BILLPARTY>Mahalaxmi Misthan Bhandar(Sec.5)</BILLPARTY></BILLFIXED>
 <BILLCL>-2076.00</BILLCL><BILLDUE>24-Dec-25</BILLDUE><BILLOVERDUE>101</BILLOVERDUE>
 <BILLFIXED><BILLDATE>24-Dec-25</BILLDATE><BILLREF>CDM/DEC25/58</BILLREF><BILLPARTY>MAYANK TRADERS SEC-4</BILLPARTY></BILLFIXED>
 <BILLCL>-582.00</BILLCL><BILLDUE>24-Dec-25</BILLDUE><BILLOVERDUE>101</BILLOVERDUE>
 <BILLFIXED><BILLDATE>24-Dec-25</BILLDATE><BILLREF>CDM/DEC25/54</BILLREF><BILLPARTY>NEW BHERUNATH DUTH DAIRY</BILLPARTY></BILLFIXED>
 <BILLCL>-2150.00</BILLCL><BILLDUE>24-Dec-25</BILLDUE><BILLOVERDUE>101</BILLOVERDUE>
 <BILLFIXED><BILLDATE>29-Dec-25</BILLDATE><BILLREF>MDLZ245</BILLREF><BILLPARTY>Mahalaxmi Misthan Bhandar(Sec.5)</BILLPARTY></BILLFIXED>
 <BILLCL>-4000.00</BILLCL><BILLDUE>29-Dec-25</BILLDUE><BILLOVERDUE>96</BILLOVERDUE>
 <BILLFIXED><BILLDATE>31-Dec-25</BILLDATE><BILLREF>MDLZ298</BILLREF><BILLPARTY>JAI AMBAY JODHPUR SWEETS &amp; BAKERY [2334955]</BILLPARTY></BILLFIXED>
 <BILLCL>-7076.00</BILLCL><BILLDUE>31-Dec-25</BILLDUE><BILLOVERDUE>94</BILLOVERDUE>
 <BILLFIXED><BILLDATE>2-Jan-26</BILLDATE><BILLREF>CDM/JAN26/30</BILLREF><BILLPARTY>ANGAD RESTORENT BALICHA</BILLPARTY></BILLFIXED>
 <BILLCL>-1237.00</BILLCL><BILLDUE>2-Jan-26</BILLDUE><BILLOVERDUE>92</BILLOVERDUE>
 <BILLFIXED><BILLDATE>3-Jan-26</BILLDATE><BILLREF>MDLZ394</BILLREF><BILLPARTY>JMB DAIRY (SAVINA)</BILLPARTY></BILLFIXED>
 <BILLCL>-1397.00</BILLCL><BILLDUE>3-Jan-26</BILLDUE><BILLOVERDUE>91</BILLOVERDUE>
 <BILLFIXED><BILLDATE>4-Jan-26</BILLDATE><BILLREF>MDLZ428</BILLREF><BILLPARTY>RAMA MEDICAL STORESEC-14</BILLPARTY></BILLFIXED>
 <BILLCL>-2187.00</BILLCL><BILLDUE>4-Jan-26</BILLDUE><BILLOVERDUE>90</BILLOVERDUE>
 <BILLFIXED><BILLDATE>5-Jan-26</BILLDATE><BILLREF>K/234</BILLREF><BILLPARTY>RAMA MEDICAL STORESEC-14</BILLPARTY></BILLFIXED>
 <BILLCL>-873.00</BILLCL><BILLDUE>5-Jan-26</BILLDUE><BILLOVERDUE>89</BILLOVERDUE>
 <BILLFIXED><BILLDATE>10-Jan-26</BILLDATE><BILLREF>MDLZ604</BILLREF><BILLPARTY>VARSHA RESTAURANT(Titardi)</BILLPARTY></BILLFIXED>
 <BILLCL>-227.00</BILLCL><BILLDUE>10-Jan-26</BILLDUE><BILLOVERDUE>84</BILLOVERDUE>
 <BILLFIXED><BILLDATE>11-Jan-26</BILLDATE><BILLREF>MDLZ630</BILLREF><BILLPARTY>SK PROVISION STORE SEC 11</BILLPARTY></BILLFIXED>
 <BILLCL>-1309.00</BILLCL><BILLDUE>11-Jan-26</BILLDUE><BILLOVERDUE>83</BILLOVERDUE>
 <BILLFIXED><BILLDATE>14-Jan-26</BILLDATE><BILLREF>MDLZ727</BILLREF><BILLPARTY>BAJRANG DUDH DAIRY &amp; GEN (RK PURAM)</BILLPARTY></BILLFIXED>
 <BILLCL>-2605.00</BILLCL><BILLDUE>14-Jan-26</BILLDUE><BILLOVERDUE>80</BILLOVERDUE>
 <BILLFIXED><BILLDATE>16-Jan-26</BILLDATE><BILLREF>CDM/JAN25/243</BILLREF><BILLPARTY>HEALTH CARE PHARMACY-Sect-3</BILLPARTY></BILLFIXED>
 <BILLCL>-1112.00</BILLCL><BILLDUE>16-Jan-26</BILLDUE><BILLOVERDUE>78</BILLOVERDUE>
 <BILLFIXED><BILLDATE>19-Jan-26</BILLDATE><BILLREF>CDM/JAN25/224</BILLREF><BILLPARTY>RAJLAXMI BAKERY(SEC.14)</BILLPARTY></BILLFIXED>
 <BILLCL>-2627.00</BILLCL><BILLDUE>19-Jan-26</BILLDUE><BILLOVERDUE>75</BILLOVERDUE>
 <BILLFIXED><BILLDATE>21-Jan-26</BILLDATE><BILLREF>MDLZ1247</BILLREF><BILLPARTY>BIKANER PRO. STORE RK PURAM</BILLPARTY></BILLFIXED>
 <BILLCL>-573.00</BILLCL><BILLDUE>21-Jan-26</BILLDUE><BILLOVERDUE>73</BILLOVERDUE>
 <BILLFIXED><BILLDATE>21-Jan-26</BILLDATE><BILLREF>MDLZ1237</BILLREF><BILLPARTY>FRIENDS ICE CREAM (UMARDA)</BILLPARTY></BILLFIXED>
 <BILLCL>-1844.00</BILLCL><BILLDUE>21-Jan-26</BILLDUE><BILLOVERDUE>73</BILLOVERDUE>
 <BILLFIXED><BILLDATE>22-Jan-26</BILLDATE><BILLREF>CDM/JAN25/255</BILLREF><BILLPARTY>JAI MEWAR JUICE SEC 6</BILLPARTY></BILLFIXED>
 <BILLCL>-1529.00</BILLCL><BILLDUE>22-Jan-26</BILLDUE><BILLOVERDUE>72</BILLOVERDUE>
 <BILLFIXED><BILLDATE>24-Jan-26</BILLDATE><BILLREF>MDLZ1351</BILLREF><BILLPARTY>KAMAKSHI STORE TITARDI</BILLPARTY></BILLFIXED>
 <BILLCL>-1336.00</BILLCL><BILLDUE>24-Jan-26</BILLDUE><BILLOVERDUE>70</BILLOVERDUE>
 <BILLFIXED><BILLDATE>28-Jan-26</BILLDATE><BILLREF>MDLZ1482</BILLREF><BILLPARTY>FRIENDS ICE CREAM (UMARDA)</BILLPARTY></BILLFIXED>
 <BILLCL>-1469.00</BILLCL><BILLDUE>28-Jan-26</BILLDUE><BILLOVERDUE>66</BILLOVERDUE>
 <BILLFIXED><BILLDATE>2-Feb-26</BILLDATE><BILLREF>CASH3517</BILLREF><BILLPARTY>MANOJ KIRANA SEC 14</BILLPARTY></BILLFIXED>
 <BILLCL>-53.00</BILLCL><BILLDUE>2-Feb-26</BILLDUE><BILLOVERDUE>61</BILLOVERDUE>
 <BILLFIXED><BILLDATE>5-Feb-26</BILLDATE><BILLREF>MDLZ1711</BILLREF><BILLPARTY>OM KIRANA SEC 14</BILLPARTY></BILLFIXED>
 <BILLCL>-307.00</BILLCL><BILLDUE>5-Feb-26</BILLDUE><BILLOVERDUE>58</BILLOVERDUE>
 <BILLFIXED><BILLDATE>6-Feb-26</BILLDATE><BILLREF>MDLZ1752</BILLREF><BILLPARTY>SAI BAKERS SEC 5</BILLPARTY></BILLFIXED>
 <BILLCL>-488.00</BILLCL><BILLDUE>6-Feb-26</BILLDUE><BILLOVERDUE>57</BILLOVERDUE>
 <BILLFIXED><BILLDATE>15-Feb-26</BILLDATE><BILLREF>CDM/FEB25/122</BILLREF><BILLPARTY>PATEL DUDH DAIRY &amp; KIRANA (EKLINGPURA)</BILLPARTY></BILLFIXED>
 <BILLCL>-3964.00</BILLCL><BILLDUE>15-Feb-26</BILLDUE><BILLOVERDUE>48</BILLOVERDUE>
 <BILLFIXED><BILLDATE>15-Feb-26</BILLDATE><BILLREF>MDLZ2074</BILLREF><BILLPARTY>RAMA MEDICAL STORESEC-14</BILLPARTY></BILLFIXED>
 <BILLCL>-3000.00</BILLCL><BILLDUE>15-Feb-26</BILLDUE><BILLOVERDUE>48</BILLOVERDUE>
 <BILLFIXED><BILLDATE>22-Feb-26</BILLDATE><BILLREF>MDLZ2289</BILLREF><BILLPARTY>MANOJ KIRANA SEC 14</BILLPARTY></BILLFIXED>
 <BILLCL>-536.00</BILLCL><BILLDUE>22-Feb-26</BILLDUE><BILLOVERDUE>41</BILLOVERDUE>
 <BILLFIXED><BILLDATE>23-Feb-26</BILLDATE><BILLREF>MDLZ2327</BILLREF><BILLPARTY>MAYANK TRADERS SEC-4</BILLPARTY></BILLFIXED>
 <BILLCL>-118.00</BILLCL><BILLDUE>23-Feb-26</BILLDUE><BILLOVERDUE>40</BILLOVERDUE>
 <BILLFIXED><BILLDATE>23-Feb-26</BILLDATE><BILLREF>525</BILLREF><BILLPARTY>SALES RETURN - GST [SRGST-12]</BILLPARTY></BILLFIXED>
 <BILLCL>-2749.96</BILLCL><BILLDUE>23-Feb-26</BILLDUE><BILLOVERDUE>40</BILLOVERDUE>
 <BILLFIXED><BILLDATE>4-Mar-26</BILLDATE><BILLREF>MDLZ2580</BILLREF><BILLPARTY>FRIENDS ICE CREAM (UMARDA)</BILLPARTY></BILLFIXED>
 <BILLCL>-4796.00</BILLCL><BILLDUE>4-Mar-26</BILLDUE><BILLOVERDUE>31</BILLOVERDUE>
 <BILLFIXED><BILLDATE>6-Mar-26</BILLDATE><BILLREF>MDLZ2640</BILLREF><BILLPARTY>KRISHNA DAIRY SEC 3</BILLPARTY></BILLFIXED>
 <BILLCL>-436.00</BILLCL><BILLDUE>6-Mar-26</BILLDUE><BILLOVERDUE>29</BILLOVERDUE>
 <BILLFIXED><BILLDATE>18-Mar-26</BILLDATE><BILLREF>MDLZ2938</BILLREF><BILLPARTY>BAJRANG DUDH DAIRY &amp; GEN (RK PURAM)</BILLPARTY></BILLFIXED>
 <BILLCL>-2259.00</BILLCL><BILLDUE>18-Mar-26</BILLDUE><BILLOVERDUE>17</BILLOVERDUE>
 <BILLFIXED><BILLDATE>18-Mar-26</BILLDATE><BILLREF>MDLZ/3</BILLREF><BILLPARTY>HEALTH CARE PHARMACY-Sect-3</BILLPARTY></BILLFIXED>
 <BILLCL>-5400.00</BILLCL><BILLDUE>18-Mar-26</BILLDUE><BILLOVERDUE>17</BILLOVERDUE>
 <BILLFIXED><BILLDATE>19-Mar-26</BILLDATE><BILLREF>MDLZ3003</BILLREF><BILLPARTY>KRISHNA DUDH DAIRY 14</BILLPARTY></BILLFIXED>
 <BILLCL>-509.00</BILLCL><BILLDUE>19-Mar-26</BILLDUE><BILLOVERDUE>16</BILLOVERDUE>
 <BILLFIXED><BILLDATE>21-Mar-26</BILLDATE><BILLREF>MDLZ3079</BILLREF><BILLPARTY>KAMAKSHI STORE TITARDI</BILLPARTY></BILLFIXED>
 <BILLCL>-721.00</BILLCL><BILLDUE>21-Mar-26</BILLDUE><BILLOVERDUE>14</BILLOVERDUE>
 <BILLFIXED><BILLDATE>22-Mar-26</BILLDATE><BILLREF>MDLZ/1</BILLREF><BILLPARTY>BIKANER PRO. STORE RK PURAM</BILLPARTY></BILLFIXED>
 <BILLCL>-263.00</BILLCL><BILLDUE>22-Mar-26</BILLDUE><BILLOVERDUE>13</BILLOVERDUE>
 <BILLFIXED><BILLDATE>24-Mar-26</BILLDATE><BILLREF>MDLZ/1</BILLREF><BILLPARTY>BAJRANG DUDH DAIRY &amp; GEN (RK PURAM)</BILLPARTY></BILLFIXED>
 <BILLCL>-8475.00</BILLCL><BILLDUE>24-Mar-26</BILLDUE><BILLOVERDUE>11</BILLOVERDUE>
 <BILLFIXED><BILLDATE>25-Mar-26</BILLDATE><BILLREF>MDLZ/5</BILLREF><BILLPARTY>MANOJ KIRANA SEC 14</BILLPARTY></BILLFIXED>
 <BILLCL>-7840.00</BILLCL><BILLDUE>25-Mar-26</BILLDUE><BILLOVERDUE>10</BILLOVERDUE>
 <BILLFIXED><BILLDATE>25-Mar-26</BILLDATE><BILLREF>MDLZ/6</BILLREF><BILLPARTY>MAYANK TRADERS SEC-4</BILLPARTY></BILLFIXED>
 <BILLCL>-4757.00</BILLCL><BILLDUE>25-Mar-26</BILLDUE><BILLOVERDUE>10</BILLOVERDUE>
 <BILLFIXED><BILLDATE>26-Mar-26</BILLDATE><BILLREF>MDLZ3212</BILLREF><BILLPARTY>KRISHNA DUDH DAIRY 14</BILLPARTY></BILLFIXED>
 <BILLCL>-3000.00</BILLCL><BILLDUE>26-Mar-26</BILLDUE><BILLOVERDUE>9</BILLOVERDUE>
 <BILLFIXED><BILLDATE>27-Mar-26</BILLDATE><BILLREF>MDLZ/2</BILLREF><BILLPARTY>FRIENDS ICE CREAM (UMARDA)</BILLPARTY></BILLFIXED>
 <BILLCL>-4757.00</BILLCL><BILLDUE>27-Mar-26</BILLDUE><BILLOVERDUE>8</BILLOVERDUE>
 <BILLFIXED><BILLDATE>29-Mar-26</BILLDATE><BILLREF>MDLZ/7</BILLREF><BILLPARTY>JAI AMBAY JODHPUR SWEETS &amp; BAKERY [2334955]</BILLPARTY></BILLFIXED>
 <BILLCL>-1800.00</BILLCL><BILLDUE>29-Mar-26</BILLDUE><BILLOVERDUE>6</BILLOVERDUE>
 <BILLFIXED><BILLDATE>30-Mar-26</BILLDATE><BILLREF>MDLZ/9</BILLREF><BILLPARTY>JAI MEWAR JUICE SEC 6</BILLPARTY></BILLFIXED>
 <BILLCL>-3866.00</BILLCL><BILLDUE>30-Mar-26</BILLDUE><BILLOVERDUE>5</BILLOVERDUE>
 <BILLFIXED><BILLDATE>30-Mar-26</BILLDATE><BILLREF>MDLZ3344</BILLREF><BILLPARTY>Mahalaxmi Misthan Bhandar(Sec.5)</BILLPARTY></BILLFIXED>
 <BILLCL>-1915.00</BILLCL><BILLDUE>30-Mar-26</BILLDUE><BILLOVERDUE>5</BILLOVERDUE>
 <BILLFIXED><BILLDATE>31-Mar-26</BILLDATE><BILLREF>MDLZ/10</BILLREF><BILLPARTY>JAY BHERAV DERY-Sect-11</BILLPARTY></BILLFIXED>
 <BILLCL>-327.00</BILLCL><BILLDUE>31-Mar-26</BILLDUE><BILLOVERDUE>4</BILLOVERDUE>
 <BILLFIXED><BILLDATE>31-Mar-26</BILLDATE><BILLREF>MDLZ/11</BILLREF><BILLPARTY>JMB DAIRY (SAVINA)</BILLPARTY></BILLFIXED>
 <BILLCL>-3150.00</BILLCL><BILLDUE>31-Mar-26</BILLDUE><BILLOVERDUE>4</BILLOVERDUE>
 <BILLFIXED><BILLDATE>2-Apr-26</BILLDATE><BILLREF>MDLZ/8</BILLREF><BILLPARTY>JAI MEWAR JUICE SEC 6</BILLPARTY></BILLFIXED>
 <BILLCL>-1449.00</BILLCL><BILLDUE>2-Apr-26</BILLDUE><BILLOVERDUE>2</BILLOVERDUE>
 <BILLFIXED><BILLDATE>2-Apr-26</BILLDATE><BILLREF>MDLZ/1</BILLREF><BILLPARTY>KRISHNA DAIRY SEC 3</BILLPARTY></BILLFIXED>
 <BILLCL>-12700.00</BILLCL><BILLDUE>2-Apr-26</BILLDUE><BILLOVERDUE>2</BILLOVERDUE>
 <BILLFIXED><BILLDATE>3-Apr-26</BILLDATE><BILLREF>MDLZ/2</BILLREF><BILLPARTY>BAJRANG DUDH DAIRY &amp; GEN (RK PURAM)</BILLPARTY></BILLFIXED>
 <BILLCL>-1488.00</BILLCL><BILLDUE>3-Apr-26</BILLDUE><BILLOVERDUE>1</BILLOVERDUE>
 <BILLFIXED><BILLDATE>3-Apr-26</BILLDATE><BILLREF>MDLZ/2</BILLREF><BILLPARTY>KRISHNA DUDH DAIRY 14</BILLPARTY></BILLFIXED>
 <BILLCL>-516.00</BILLCL><BILLDUE>3-Apr-26</BILLDUE><BILLOVERDUE>1</BILLOVERDUE>
 <BILLFIXED><BILLDATE>4-Apr-26</BILLDATE><BILLREF>MDLZ/1</BILLREF><BILLPARTY>ANGAD RESTORENT BALICHA</BILLPARTY></BILLFIXED>
 <BILLCL>-4350.00</BILLCL><BILLDUE>4-Apr-26</BILLDUE><BILLOVERDUE>0</BILLOVERDUE>
 <BILLFIXED><BILLDATE>4-Apr-26</BILLDATE><BILLREF>MDLZ/13</BILLREF><BILLPARTY>KAMAKSHI STORE TITARDI</BILLPARTY></BILLFIXED>
 <BILLCL>-1658.00</BILLCL><BILLDUE>4-Apr-26</BILLDUE><BILLOVERDUE>0</BILLOVERDUE>
 <BILLFIXED><BILLDATE>4-Apr-26</BILLDATE><BILLREF>MDLZ/3</BILLREF><BILLPARTY>Mahalaxmi Misthan Bhandar(Sec.5)</BILLPARTY></BILLFIXED>
 <BILLCL>-516.00</BILLCL><BILLDUE>4-Apr-26</BILLDUE><BILLOVERDUE>0</BILLOVERDUE>
</ENVELOPE>"""

root = ET.fromstring(XML_RAW)
children = list(root)

bills = []
i = 0
while i < len(children):
    child = children[i]
    if child.tag == "BILLFIXED":
        bill_date  = (child.findtext("BILLDATE") or "").strip()
        bill_ref   = (child.findtext("BILLREF")  or "").strip()
        bill_party = (child.findtext("BILLPARTY") or "").strip()
        bill_cl = bill_due = bill_overdue = ""
        if i+1 < len(children) and children[i+1].tag == "BILLCL":
            bill_cl = (children[i+1].text or "").strip()
        if i+2 < len(children) and children[i+2].tag == "BILLDUE":
            bill_due = (children[i+2].text or "").strip()
        if i+3 < len(children) and children[i+3].tag == "BILLOVERDUE":
            bill_overdue = (children[i+3].text or "").strip()
        amount = round(abs(float(bill_cl)), 2) if bill_cl else 0.0
        bills.append({
            "bill_date":    bill_date,
            "bill_ref":     bill_ref,
            "party_name":   bill_party,
            "amount":       amount,
            "due_date":     bill_due,
            "overdue_days": int(bill_overdue) if bill_overdue else 0,
        })
        i += 4
    else:
        i += 1

# Aggregate outstanding per party (insertion order preserved in Python 3.7+)
party_totals = {}
for b in bills:
    p = b["party_name"]
    party_totals[p] = round(party_totals.get(p, 0.0) + b["amount"], 2)

parties = [{"party_name": k, "outstanding": v} for k, v in party_totals.items()]
grand_total = round(sum(p["outstanding"] for p in parties), 2)

result = {
    "as_of_date":   "04-04-2026",
    "ledger_group": "Sundry Debtors",
    "fetched_on":   "21-03-2026",
    "grand_total":  grand_total,
    "parties":      parties,
    "bills":        bills,
}

# Use Windows-native path so Python can open it correctly
out_dir = r"C:\Users\Dell\Documents\TallyMCPServer\receivables-dashboard\output"
os.makedirs(out_dir, exist_ok=True)
out_path = os.path.join(out_dir, "receivables.json")
with open(out_path, "w", encoding="utf-8") as f:
    json.dump(result, f, indent=2, ensure_ascii=False)

print(f"Parties: {len(parties)}, Grand Total: {grand_total}")
for p in parties:
    print(f"  {p['party_name']}  =>  {p['outstanding']}")
